
const API='https://jwbrygmzruoxihmjqazg.supabase.co/functions/v1/election-2026-panel';
const TSE='https://cdn.tse.jus.br/estatistica/sead/eleicoes/eleicoes2026/buweb/bweb_1t_CE_051020261403.zip';
const $=i=>document.getElementById(i), dg=v=>String(v??'').replace(/\.0$/,'').replace(/\D/g,''), cl=v=>(dg(v).replace(/^0+/,'')||'0'), pad=(v,n)=>cl(v).padStart(n,'0'), nm=s=>String(s??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().replace(/[^A-Z0-9]/g,'');
let pw=sessionStorage.getItem('electionPassword')||'', boot={lists:[],candidates:[]}, places=[], votes=[], sections=[], active=new Set(), leonardoHist=null, leoSort='2026desc', leoMin=0;
const fmt=n=>Number(n||0).toLocaleString('pt-BR');
function toast(m){let x=document.createElement('div');x.className='toast';x.textContent=m;document.body.appendChild(x);setTimeout(()=>x.remove(),3000)}
async function api(action,extra){let r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.assign({password:pw,action:action},extra||{}))}),t=await r.text(),d={};try{d=JSON.parse(t)}catch{}if(!r.ok)throw Error(d.error||('Erro '+r.status));return d}
function login(err){$('app').innerHTML='<div class="login"><div class="loginCard"><h1>🗳️ Painel Eleições 2026</h1><p>Área restrita.</p><div class="loginRow"><input id="pass" type="password" placeholder="Senha" autofocus><button id="go" class="btn orange">Entrar</button></div><div class="loginErr">'+(err||'')+'</div></div></div>';$('go').onclick=enter;$('pass').onkeydown=e=>{if(e.key==='Enter')enter()}}
async function enter(){pw=$('pass').value;try{await api('auth');sessionStorage.setItem('electionPassword',pw);start()}catch{pw='';login('Senha incorreta.')}}
async function start(){try{await api('auth')}catch{return login()} shell();try{await Promise.all([loadBoot(),loadPlaces(),loadLeonardo()]);drawCands();drawLists();drawOfficial();drawLeonardo();await workData()}catch(e){toast(e.message)}}
function shell(){
 let h=[];
 h.push('<div class="wrap"><div class="top"><div><h1>🗳️ Painel Eleições 2026</h1><div class="sub">Votação oficial e área de trabalho separadas.</div><span class="okpill">BASE DE BAIRROS/SEÇÕES FIXA</span></div><button id="logout" class="btn red">Sair</button></div>');
 h.push('<div class="nav"><button class="active" data-p="official">📊 VOTAÇÃO OFICIAL</button><button data-p="work">📁 LISTAS & TRABALHO</button><button data-p="leonardo">🟠 LEONARDO • HISTÓRICO</button></div>');
 h.push('<section id="official" class="page active"><div class="grid2"><div class="card"><div class="title">1. Carregar votos do TSE</div><div class="hint">Único arquivo grande manual. Bairros, locais, zonas e seções já ficam no site.</div><div class="actions"><a class="btn dark" href="'+TSE+'">Baixar votos CE</a></div><input id="voteFile" class="file" type="file" accept=".zip,.csv"><div id="voteStatus" class="status">Aguardando o arquivo de votos.</div><div class="progress"><div id="voteProg"></div></div></div>');
 h.push('<div class="card"><div class="title">2. Candidatos da análise</div><div class="hint">Pode usar só Leonardo, Leonardo + Nenen, ou cadastrar outro candidato.</div><div id="candChips" class="candidates" style="margin-top:9px"></div><div class="candidateForm"><div class="field"><label>Nome</label><input id="candName" type="text"></div><div class="field"><label>Número</label><input id="candNumber" type="text"></div><div class="field"><label>Cargo</label><input id="candOffice" type="text"></div><div class="field"><label>Cor</label><input id="candColor" type="color" value="#f47c20"></div><button id="saveCand" class="btn blue">+ Cadastrar</button></div></div></div>');
 h.push('<div id="officialMetrics" class="metrics"></div><div class="card"><div class="filters"><div class="field"><label>Município</label><select id="city"></select></div><div class="field"><label>Bairro</label><select id="bairro"></select></div><div class="field"><label>Zona</label><select id="zone"></select></div><div class="field"><label>Seção</label><input id="section" type="text" placeholder="0184"></div></div><div class="actions"><button id="refreshOfficial" class="btn dark">Atualizar</button><button id="exportOfficial" class="btn outline">Exportar CSV</button><span id="offTag" class="tag"></span></div><div class="tableWrap"><table><thead id="offHead"></thead><tbody id="offBody"></tbody></table></div></div></section>');
 h.push('<section id="work" class="page"><div class="gridWork"><aside class="card"><div class="title">Listas salvas</div><div class="hint">Disponíveis em qualquer computador/celular que entrar no painel.</div><div id="savedLists" style="margin-top:10px"></div><div class="sep"></div><div class="title">Adicionar / substituir lista</div><div class="field"><label>Nome da lista</label><input id="listName" type="text" placeholder="Ex.: Liderança João"></div><input id="listFile" class="file" type="file" accept=".odt,.xlsx,.xls,.ods,.csv,.tsv,.txt,.json"><button id="saveList" class="btn blue" style="width:100%;margin-top:8px">Salvar lista no painel</button><div id="listStatus" class="status">Nenhum arquivo selecionado.</div></aside>');
 h.push('<main><div id="workMetrics" class="metrics"></div><div class="card"><div class="filters"><div class="field"><label>Bairro</label><select id="wBairro"></select></div><div class="field"><label>Local</label><select id="wLocal"></select></div><div class="field"><label>Zona</label><select id="wZone"></select></div><div class="field"><label>Seção</label><input id="wSection" type="text" placeholder="0184"></div></div><div class="actions"><button id="refreshWork" class="btn dark">Atualizar</button><button id="exportWork" class="btn outline">Exportar comparação</button><span id="workTag" class="tag"></span></div></div><div class="grid2" style="margin-top:12px"><div class="card"><div class="title">Concentração por bairro</div><div id="workBars" class="bars"></div></div><div class="card"><div class="title">Resumo das listas</div><div id="listSummary"></div></div></div><div class="card" style="margin-top:12px"><div class="title">Seções das listas</div><div class="hint">Os votos são totais agregados da seção, não votos atribuídos às pessoas da lista.</div><div class="tableWrap"><table><thead id="workHead"></thead><tbody id="workBody"></tbody></table></div></div></main></div></section>');
 h.push('<section id="leonardo" class="page"><div class="leoHero"><div><div class="eyebrow">LEONARDO PINHEIRO • DEPUTADO ESTADUAL</div><h2>Votação por município</h2><p>Histórico de 2006 a 2026, comparação municipal e análise para impressão.</p></div><div class="leoHeroBadge">40999</div></div><div id="leoSummary" class="leoSummary"></div><div class="card leoTools"><div class="leoSearch"><input id="leoSearch" type="text" placeholder="Buscar município"></div><div><div class="leoSorts"><button class="leoSort active" data-sort="2026desc">Mais votos 2026</button><button class="leoSort" data-sort="alpha">Alfabética</button><button class="leoSort" data-sort="cresceu">Maior ganho em votos</button><button class="leoSort" data-sort="caiu">Maior queda em votos</button><button class="leoSort" data-sort="2022desc">Mais votos 2022</button></div><div class="leoThresholds"><span>Faixa 2026:</span><button class="leoMin active" data-min="0">Todos</button><button class="leoMin" data-min="100">≥ 100</button><button class="leoMin" data-min="300">≥ 300</button><button class="leoMin" data-min="500">≥ 500</button><button class="leoMin" data-min="1000">≥ 1.000</button></div></div><div class="actions"><button id="leoExport" class="btn outline">Baixar planilha</button><button id="leoPrint" class="btn orange">Imprimir</button><span id="leoTag" class="tag"></span></div></div><div class="grid2 leoCharts"><div class="card"><div class="title">Evolução total por eleição</div><div id="leoTrend" class="trend"></div></div><div class="card"><div class="title">Top municípios em 2026</div><div id="leoTop" class="bars"></div></div></div><div class="card" style="margin-top:12px"><div class="title">Município por município</div><div class="hint">A coluna 2026 é preenchida automaticamente pelo mesmo arquivo do TSE carregado na primeira aba.</div><div class="tableWrap leoTable"><table><thead><tr><th>Nº</th><th>Município</th><th class="num">Eleitores</th><th class="num">2006</th><th class="num">2010</th><th class="num">2014</th><th class="num">2018</th><th class="num">2022</th><th class="num leo2026">2026</th><th class="num">Dif. votos</th><th class="num">% 22→26</th></tr></thead><tbody id="leoBody"></tbody></table></div></div></section>');
 h.push('</div>');
 $('app').innerHTML=h.join('');
 document.querySelectorAll('.nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav button').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(b.dataset.p).classList.add('active');if(b.dataset.p==='work')workData();if(b.dataset.p==='leonardo')drawLeonardo()});
 $('logout').onclick=()=>{sessionStorage.removeItem('electionPassword');pw='';login()}; $('voteFile').onchange=loadVotes; $('saveCand').onclick=saveCand; $('refreshOfficial').onclick=drawOfficial; $('exportOfficial').onclick=exportOfficial; ['city','bairro','zone'].forEach(i=>$(i).onchange=drawOfficial); $('section').oninput=drawOfficial; $('saveList').onclick=saveList; $('refreshWork').onclick=drawWork; $('exportWork').onclick=exportWork; ['wBairro','wLocal','wZone'].forEach(i=>$(i).onchange=drawWork); $('wSection').oninput=drawWork; $('leoSearch').oninput=drawLeonardo; document.querySelectorAll('.leoSort').forEach(x=>x.onclick=()=>{leoSort=x.dataset.sort;document.querySelectorAll('.leoSort').forEach(y=>y.classList.remove('active'));x.classList.add('active');drawLeonardo()}); document.querySelectorAll('.leoMin').forEach(x=>x.onclick=()=>{leoMin=Number(x.dataset.min||0);document.querySelectorAll('.leoMin').forEach(y=>y.classList.remove('active'));x.classList.add('active');drawLeonardo()}); $('leoExport').onclick=exportLeonardo; $('leoPrint').onclick=()=>window.print();
}
async function loadBoot(){boot=await api('bootstrap');active=new Set(boot.candidates.filter(c=>c.enabled).map(c=>String(c.number)))}
async function loadLeonardo(){leonardoHist=await fetch('/data/leonardo-historico.json').then(r=>r.json())}
async function loadPlaces(){let us=Array.from({length:11},(_,i)=>'/data/locais-'+String(i).padStart(2,'0')+'.csv'),ts=await Promise.all(us.map(u=>fetch(u).then(r=>r.text())));places=[];ts.forEach((t,i)=>{Papa.parse(t,{delimiter:';',skipEmptyLines:true}).data.forEach((a,j)=>{if(i===0&&j===0)return;if(a.length>=5)places.push({city:String(a[0]||'').trim(),zone:pad(a[1],3),sec:pad(a[2],4),bairro:String(a[3]||'SEM BAIRRO').trim(),local:String(a[4]||'').trim()})})});fillCities()}
function drawCands(){$('candChips').innerHTML=boot.candidates.map(c=>'<label class="cand"><input class="cc" type="checkbox" value="'+c.number+'" '+(active.has(String(c.number))?'checked':'')+'><span class="dot" style="background:'+c.color+'"></span><span><b>'+c.name+'</b> <small>'+c.number+' • '+(c.office||'')+'</small></span></label>').join('');document.querySelectorAll('.cc').forEach(x=>x.onchange=()=>{x.checked?active.add(x.value):active.delete(x.value);drawOfficial();drawWork();drawLeonardo()})}
async function saveCand(){let c={name:$('candName').value.trim(),number:$('candNumber').value.trim(),office:$('candOffice').value.trim(),color:$('candColor').value.trim()||'#667085',enabled:true};if(!c.name||!dg(c.number))return toast('Informe nome e número.');try{await api('save_candidate',{candidate:c});boot=await api('bootstrap');active.add(dg(c.number));drawCands();toast('Candidato cadastrado. Recarregue os votos para incluir esse número.')}catch(e){toast(e.message)}}
function pick(cs,ns){for(let n of ns){for(let c of cs)if(nm(c)===nm(n))return c}for(let n of ns){for(let c of cs)if(nm(c).includes(nm(n)))return c}return null}
async function csvFile(f){if(!f.name.toLowerCase().endsWith('.zip'))return f;let z=await JSZip.loadAsync(await f.arrayBuffer()),cs=Object.values(z.files).filter(x=>x.name.toLowerCase().endsWith('.csv'));cs.sort((a,b)=>(b._data?.uncompressedSize||0)-(a._data?.uncompressedSize||0));if(!cs.length)throw Error('CSV não encontrado no ZIP.');return new File([await cs[0].async('uint8array')],cs[0].name,{type:'text/csv'})}
async function loadVotes(e){let f0=e.target.files[0];if(!f0)return;$('voteStatus').textContent='Abrindo arquivo…';$('voteProg').parentElement.style.display='block';try{let f=await csvFile(f0),nums=new Set(boot.candidates.map(c=>String(c.number))),cfg=null,n=0;votes=[];await new Promise((ok,fail)=>Papa.parse(f,{header:true,delimiter:';',encoding:'ISO-8859-1',worker:true,skipEmptyLines:true,chunkSize:2097152,chunk:r=>{if(!cfg){let k=r.meta.fields||[];cfg={city:pick(k,['NM_MUNICIPIO']),z:pick(k,['NR_ZONA']),s:pick(k,['NR_SECAO']),num:pick(k,['NR_VOTAVEL']),v:pick(k,['QT_VOTOS'])};if(!cfg.city||!cfg.z||!cfg.s||!cfg.num||!cfg.v){fail(Error('Colunas do TSE não reconhecidas.'));return}}for(let a of r.data){let num=cl(a[cfg.num]);if(nums.has(num))votes.push({city:String(a[cfg.city]||'').trim(),zone:pad(a[cfg.z],3),sec:pad(a[cfg.s],4),num:num,votes:parseInt(dg(a[cfg.v])||0)})}n+=r.data.length;if(n%100000<5000){$('voteStatus').textContent='Processando… '+fmt(n)+' linhas';$('voteProg').style.width=Math.min(96,5+n/200000)+'%'}},complete:ok,error:fail}));$('voteProg').style.width='100%';$('voteStatus').textContent='Pronto: '+fmt(votes.length)+' registros dos candidatos cadastrados.';$('voteStatus').className='status ok';drawOfficial();drawWork();drawLeonardo();toast('Votos carregados.')}catch(e){$('voteStatus').textContent='Erro: '+e.message;$('voteStatus').className='status err'}}
function fillCities(){let old=$('city')?$('city').value:'',cs=[...new Set(places.map(x=>x.city).filter(Boolean))].sort();$('city').innerHTML='<option value="">Todos os municípios</option>'+cs.map(x=>'<option '+(x===old?'selected':'')+'>'+x+'</option>').join('');if(!old&&cs.includes('FORTALEZA'))$('city').value='FORTALEZA'}
function vmap(){let m=new Map();for(let r of votes){let k=r.city+'|'+r.zone+'|'+r.sec;if(!m.has(k))m.set(k,{});m.get(k)[r.num]=(m.get(k)[r.num]||0)+r.votes}return m}
function refill(){let city=$('city').value,bo=$('bairro').value,zo=$('zone').value,p=places.filter(x=>!city||x.city===city),bs=[...new Set(p.map(x=>x.bairro).filter(Boolean))].sort();$('bairro').innerHTML='<option value="">Todos os bairros</option>'+bs.map(x=>'<option '+(x===bo?'selected':'')+'>'+x+'</option>').join('');p=p.filter(x=>!$('bairro').value||x.bairro===$('bairro').value);let zs=[...new Set(p.map(x=>x.zone))].sort();$('zone').innerHTML='<option value="">Todas</option>'+zs.map(x=>'<option '+(x===zo?'selected':'')+'>'+x+'</option>').join('')}
function offRows(){let c=$('city').value,b=$('bairro').value,z=$('zone').value,s=$('section').value.trim()?pad($('section').value,4):'',vm=vmap();return places.filter(p=>(!c||p.city===c)&&(!b||p.bairro===b)&&(!z||p.zone===z)&&(!s||p.sec===s)).map(p=>Object.assign({},p,{v:vm.get(p.city+'|'+p.zone+'|'+p.sec)||{}}))}
function drawOfficial(){if(!$('official'))return;refill();let rs=offRows(),sel=boot.candidates.filter(c=>active.has(String(c.number)));$('officialMetrics').innerHTML='<div class="metric"><small>Seções exibidas</small><b>'+fmt(rs.length)+'</b></div><div class="metric"><small>Bairros</small><b>'+fmt(new Set(rs.map(r=>r.bairro)).size)+'</b></div>'+sel.slice(0,2).map(c=>'<div class="metric dynamic" style="--c:'+c.color+'"><small>'+c.name+' '+c.number+'</small><b style="color:'+c.color+'">'+fmt(rs.reduce((a,r)=>a+(r.v[c.number]||0),0))+'</b></div>').join('');$('offHead').innerHTML='<tr><th>Bairro</th><th>Local</th><th>Zona</th><th>Seção</th>'+sel.map(c=>'<th class="num" style="color:'+c.color+'">'+c.name+'</th>').join('')+'</tr>';$('offBody').innerHTML=rs.slice(0,3000).map(r=>'<tr><td>'+r.bairro+'</td><td>'+r.local+'</td><td class="center">'+r.zone+'</td><td class="center">'+r.sec+'</td>'+sel.map(c=>'<td class="num" style="color:'+c.color+';font-weight:850">'+fmt(r.v[c.number]||0)+'</td>').join('')+'</tr>').join('');$('offTag').textContent=rs.length+' seções'}
function exp(name,rows){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+Papa.unparse(rows,{delimiter:';'})],{type:'text/csv'}));a.download=name;a.click()}
function exportOfficial(){let sel=boot.candidates.filter(c=>active.has(String(c.number)));exp('votacao_oficial.csv',offRows().map(r=>Object.assign({Municipio:r.city,Bairro:r.bairro,Local:r.local,Zona:r.zone,Secao:r.sec},Object.fromEntries(sel.map(c=>[c.name+' '+c.number,r.v[c.number]||0])))))}
function drawLists(){$('savedLists').innerHTML=boot.lists.map(l=>'<label class="listCard"><input type="checkbox" class="lc" value="'+l.id+'" checked><span><b>'+l.name+'</b><small>'+fmt(l.people_count)+' pessoas • '+fmt(l.sections_count)+' seções</small></span></label>').join('');document.querySelectorAll('.lc').forEach(x=>x.onchange=workData)}
async function parseList(f){let b=await f.arrayBuffer(),n=f.name.toLowerCase(),r=[];if(/\.(csv|tsv|txt)$/.test(n))r=Papa.parse(new TextDecoder('latin1').decode(b),{header:true,delimiter:n.endsWith('.tsv')?'\t':'',skipEmptyLines:true}).data;else if(n.endsWith('.json')){let d=JSON.parse(new TextDecoder().decode(b));r=Array.isArray(d)?d:Object.values(d).find(Array.isArray)||[]}else if(/\.(xlsx|xls|ods)$/.test(n)){let w=XLSX.read(b,{type:'array'});r=XLSX.utils.sheet_to_json(w.Sheets[w.SheetNames[0]],{defval:''})}else if(n.endsWith('.odt')){let z=await JSZip.loadAsync(b),x=await z.file('content.xml').async('string'),d=new DOMParser().parseFromString(x,'text/xml'),rs=[...d.getElementsByTagNameNS('*','table-row')].map(tr=>[...tr.getElementsByTagNameNS('*','table-cell')].map(td=>td.textContent.trim())).filter(x=>x.some(Boolean)),h=rs.findIndex(x=>nm(x.join(' ')).includes('ZONA')&&nm(x.join(' ')).includes('SECAO'));if(h<0)h=0;let hd=rs[h].map((x,i)=>String(x||'C'+i).trim());r=rs.slice(h+1).map(x=>Object.fromEntries(hd.map((c,i)=>[c,x[i]||''])))}if(!r.length)return[];let cs=Object.keys(r[0]),z=pick(cs,['ZONA','NR_ZONA']),s=pick(cs,['SECAO','SEÇÃO','NR_SECAO']),na=pick(cs,['NOME COMPLETO','NOME']);if(!z||!s)throw Error('Não encontrei Zona e Seção.');return r.map(x=>({name:na?String(x[na]||'').trim():'Pessoa',zone:pad(x[z],3),section:pad(x[s],4)})).filter(x=>x.zone!=='000'&&x.section!=='0000')}
async function saveList(){let f=$('listFile').files[0],name=$('listName').value.trim()||(f?f.name.replace(/\.[^.]+$/,''):'');if(!f||!name)return toast('Escolha o arquivo e informe o nome.');$('listStatus').textContent='Lendo e salvando…';try{let rows=await parseList(f),r=await api('save_list',{name:name,rows:rows});$('listStatus').textContent='Salva: '+fmt(r.people_count)+' pessoas • '+fmt(r.sections_count)+' seções.';$('listStatus').className='status ok';boot=await api('bootstrap');drawCands();drawLists();await workData()}catch(e){$('listStatus').textContent='Erro: '+e.message;$('listStatus').className='status err'}}
async function workData(){let ids=[...document.querySelectorAll('.lc:checked')].map(x=>x.value);try{sections=ids.length?await api('sections',{list_ids:ids}):[];drawWork()}catch(e){toast(e.message)}}
function workBase(){let city=$('city').value||'FORTALEZA',vm=vmap(),pm=new Map();for(let p of places)if(!city||p.city===city)pm.set(p.zone+'|'+p.sec,p);let ag=new Map();for(let s of sections){let k=s.zone+'|'+s.section;if(!ag.has(k))ag.set(k,{zone:s.zone,sec:s.section,people:0,lists:new Set()});let a=ag.get(k);a.people+=Number(s.people_count||0);a.lists.add(s.list_name)}return [...ag].map(([k,a])=>{let p=pm.get(k)||{},v=vm.get((p.city||city)+'|'+a.zone+'|'+a.sec)||{};return Object.assign({},a,{bairro:p.bairro||'',local:p.local||'',v:v,lists:[...a.lists].join(', ')})})}
function wfill(base){let bo=$('wBairro').value,lo=$('wLocal').value,zo=$('wZone').value,bs=[...new Set(base.map(x=>x.bairro).filter(Boolean))].sort();$('wBairro').innerHTML='<option value="">Todos os bairros</option>'+bs.map(x=>'<option '+(x===bo?'selected':'')+'>'+x+'</option>').join('');let f=base.filter(x=>!$('wBairro').value||x.bairro===$('wBairro').value),ls=[...new Set(f.map(x=>x.local).filter(Boolean))].sort(),zs=[...new Set(f.map(x=>x.zone))].sort();$('wLocal').innerHTML='<option value="">Todos os locais</option>'+ls.map(x=>'<option '+(x===lo?'selected':'')+'>'+x+'</option>').join('');$('wZone').innerHTML='<option value="">Todas</option>'+zs.map(x=>'<option '+(x===zo?'selected':'')+'>'+x+'</option>').join('')}
function wrows(){let b=$('wBairro').value,l=$('wLocal').value,z=$('wZone').value,s=$('wSection').value.trim()?pad($('wSection').value,4):'';return workBase().filter(r=>(!b||r.bairro===b)&&(!l||r.local===l)&&(!z||r.zone===z)&&(!s||r.sec===s)).sort((a,b)=>b.people-a.people)}
function drawWork(){if(!$('work'))return;let base=workBase();wfill(base);let rs=wrows(),sel=boot.candidates.filter(c=>active.has(String(c.number)));$('workMetrics').innerHTML='<div class="metric"><small>Pessoas nas listas</small><b>'+fmt(rs.reduce((a,r)=>a+r.people,0))+'</b></div><div class="metric"><small>Seções cobertas</small><b>'+fmt(rs.length)+'</b></div>'+sel.slice(0,2).map(c=>'<div class="metric dynamic" style="--c:'+c.color+'"><small>'+c.name+' nessas seções</small><b style="color:'+c.color+'">'+fmt(rs.reduce((a,r)=>a+(r.v[c.number]||0),0))+'</b></div>').join('');$('workHead').innerHTML='<tr><th>Bairro</th><th>Local</th><th>Zona</th><th>Seção</th><th class="num">Pessoas</th>'+sel.map(c=>'<th class="num" style="color:'+c.color+'">'+c.name+'</th>').join('')+'<th>Lista(s)</th></tr>';$('workBody').innerHTML=rs.map(r=>'<tr><td>'+(r.bairro||'—')+'</td><td>'+(r.local||'—')+'</td><td>'+r.zone+'</td><td>'+r.sec+'</td><td class="num"><b>'+fmt(r.people)+'</b></td>'+sel.map(c=>'<td class="num" style="color:'+c.color+';font-weight:850">'+fmt(r.v[c.number]||0)+'</td>').join('')+'<td>'+r.lists+'</td></tr>').join('');$('workTag').textContent=rs.length+' seções';let bm=new Map(),tot=rs.reduce((a,r)=>a+r.people,0);for(let r of rs){let k=r.bairro||'SEM BAIRRO';bm.set(k,(bm.get(k)||0)+r.people)}let ar=[...bm].sort((a,b)=>b[1]-a[1]).slice(0,10),mx=Math.max(1,...ar.map(x=>x[1]));$('workBars').innerHTML=ar.map(x=>'<div class="barrow"><div>'+x[0]+'</div><div class="barbg"><div class="barfill" style="width:'+(x[1]/mx*100)+'%"></div></div><b>'+(tot?(x[1]/tot*100).toFixed(1):0)+'%</b></div>').join('');$('listSummary').innerHTML=boot.lists.map(l=>'<div class="listCard"><span><b>'+l.name+'</b><small>'+fmt(l.people_count)+' pessoas • '+fmt(l.sections_count)+' seções</small></span></div>').join('')}
function exportWork(){let sel=boot.candidates.filter(c=>active.has(String(c.number)));exp('comparacao_listas.csv',wrows().map(r=>Object.assign({Bairro:r.bairro,Local:r.local,Zona:r.zone,Secao:r.sec,Pessoas:r.people,Listas:r.lists},Object.fromEntries(sel.map(c=>[c.name+' '+c.number,r.v[c.number]||0])))))}

function leo2026ByCity(){
 let m=new Map();
 for(let r of votes){if(String(r.num)!=='40999')continue;let k=nm(r.city);m.set(k,(m.get(k)||0)+Number(r.votes||0))}
 return m;
}
function leoRows(){
 if(!leonardoHist)return[];
 let q=nm($('leoSearch')?.value||'');
 let a=leonardoHist.municipios.map(x=>Object.assign({},x,{v2026:Number(x['2026']||0),diff:Number(x['2026']||0)-Number(x['2022']||0)}));
 if(q)a=a.filter(x=>nm(x.municipio).includes(q));
 if(leoMin)a=a.filter(x=>x.v2026>=leoMin);
 if(leoSort==='alpha')a.sort((a,b)=>a.municipio.localeCompare(b.municipio,'pt-BR'));
 else if(leoSort==='2022desc')a.sort((a,b)=>b['2022']-a['2022']);
 else if(leoSort==='cresceu')a=a.filter(x=>x.diff>0).sort((a,b)=>b.diff-a.diff);
 else if(leoSort==='caiu')a=a.filter(x=>x.diff<0).sort((a,b)=>a.diff-b.diff);
 else a.sort((a,b)=>b.v2026-a.v2026);
 return a;
}
function drawLeonardo(){
 if(!$('leonardo')||!leonardoHist)return;
 let all=leonardoHist.municipios.map(x=>Object.assign({},x,{v2026:Number(x['2026']||0)}));
 let total26=Number(leonardoHist.source_totals['2026']||all.reduce((a,x)=>a+x.v2026,0)),total22=Number(leonardoHist.source_totals['2022']||0),diff=total26-total22,pct=total22?diff/total22*100:0,cres=all.filter(x=>x.v2026>x['2022']).length,cai=all.filter(x=>x.v2026<x['2022']).length,iguais=all.filter(x=>x.v2026===x['2022']).length;
 $('leoSummary').innerHTML='<div class="leoBig"><small>2022 • eleito</small><b>'+fmt(total22)+'</b></div><div class="leoArrow">→</div><div class="leoBig"><small>2026 • suplente</small><b>'+fmt(total26)+'</b></div><div class="leoDelta '+(diff>=0?'up':'down')+'"><b>'+(pct>=0?'+':'')+pct.toFixed(1)+'%</b><small>'+(diff>=0?'+':'')+fmt(diff)+' votos</small></div>';
 let totals=[['2006',leonardoHist.source_totals['2006']],['2010',leonardoHist.source_totals['2010']],['2014',leonardoHist.source_totals['2014']],['2018',leonardoHist.source_totals['2018']],['2022',total22],['2026',total26]],mx=Math.max(...totals.map(x=>x[1]));
 $('leoTrend').innerHTML=totals.map(x=>'<div class="trendRow"><span>'+x[0]+'</span><div class="trendBg"><div class="trendFill" style="width:'+(x[1]/mx*100)+'%"></div></div><b>'+fmt(x[1])+'</b></div>').join('');
 let top=[...all].sort((a,b)=>b.v2026-a.v2026).slice(0,10),tm=Math.max(1,...top.map(x=>x.v2026));
 $('leoTop').innerHTML=top.map(x=>'<div class="barrow"><div>'+x.municipio+'</div><div class="barbg"><div class="barfill orangeFill" style="width:'+(x.v2026/tm*100)+'%"></div></div><b>'+fmt(x.v2026)+'</b></div>').join('');
 let rows=leoRows();
 $('leoBody').innerHTML=rows.map(x=>{let d=x.v2026-x['2022'],p=x['2022']?d/x['2022']*100:null,low=x['2022']<100;return '<tr><td class="center">'+x.n+'</td><td><b>'+x.municipio+'</b></td><td class="num">'+fmt(x.eleitores)+'</td><td class="num">'+fmt(x['2006'])+'</td><td class="num">'+fmt(x['2010'])+'</td><td class="num">'+fmt(x['2014'])+'</td><td class="num">'+fmt(x['2018'])+'</td><td class="num">'+fmt(x['2022'])+'</td><td class="num leo2026"><b>'+fmt(x.v2026)+'</b></td><td class="num"><span class="'+(d>=0?'diffUp':'diffDown')+'">'+(d>=0?'+':'')+fmt(d)+'</span></td><td class="num">'+(p===null?'—':('<span class="'+(p>=0?'pctUp':'pctDown')+'">'+(p>=0?'▲ ':'▼ ')+Math.abs(p).toFixed(1)+'%</span>'+(low?'<small class="lowBase">base baixa</small>':'')))+'</td></tr>'}).join('');
 $('leoTag').textContent=rows.length+' municípios • '+cres+' cresceram • '+cai+' caíram'+(iguais?' • '+iguais+' iguais':'')+(leoMin?' • filtro ≥ '+fmt(leoMin)+' votos':'');
}
function exportLeonardo(){
 if(!leonardoHist)return;
 exp('leonardo_votacao_por_municipio.csv',leoRows().map(x=>({Municipio:x.municipio,Eleitores:x.eleitores,'2006':x['2006'],'2010':x['2010'],'2014':x['2014'],'2018':x['2018'],'2022':x['2022'],'2026':x.v2026,Diferenca_votos:x.v2026-x['2022'],Variacao_pct:x['2022']?((x.v2026-x['2022'])/x['2022']*100).toFixed(1):'',Observacao:x['2022']<100?'Base 2022 baixa':''})))
}

if(pw)start();else login();
